### ISSUE TITLE
Install - step 1

### ISSUE THREAD

**Issue by xerostomus** [stefets/live-config#119]
Thank you, Sirs, for keeping mididings alive, but it is very VERY difficult task to install it. I have already spent a few hours trying to cope... :-(

https://github.com/stefets/live-config/wiki/Step-1-:-Setup-just-(WIP)

git clone 'https://mpr.makedeb.org/just'
bash -ci "$(wget -qO - 'https://shlink.makedeb.org/install')"
Select makedeb in the choices
makedeb -si

The last step "makedeb -si" needs Cargo. 
Installing Cargo demands almost 900 MB.  (Es müssen noch 155 MB von 155 MB an Archiven heruntergeladen werden.
Nach dieser Operation werden 858 MB Plattenplatz zusätzlich benutzt.)
Is there some way how to install it without this GB of extra data?

Thank you

Sincerely

Xerostomus

PS I would appreciate if there were somethink like: 
MuseScore-4.1.1.232071203-x86_64.AppImage
So some file which runs without these crazy procedures.
If possible? :-)

Anyway installing Cargo was of no help:

makedeb -si
[#] Making package: just 1.14.0-2 (St 27. prosince 2023, 21:03:49)
[#] Checking for missing dependencies...
[#] Installing missing dependencies...
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
Einige Pakete konnten nicht installiert werden. Das kann bedeuten, dass
Sie eine unmögliche Situation angefordert haben oder, wenn Sie die
Unstable-Distribution verwenden, dass einige erforderliche Pakete noch
nicht erstellt wurden oder Incoming noch nicht verlassen haben.
Die folgenden Informationen helfen Ihnen vielleicht, die Situation zu lösen:

Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 satisfy:command-line : Hängt ab von: cargo (>= 1.63) aber 0.66.0+ds1-1 soll installiert werden
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.
[!] Failed to install missing dependencies. 

I am totaly lost.

**Comment by stefets** [comment]
Hi! You can give up with my procedure because it will change and it is not up to date, forget Cargo.

A fresh pull request suggest a new build system that looks promising https://github.com/mididings/mididings/pull/16 so I will update my procedure when the new build system will be merged.

Regards
